apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - name: mynode
      image: sit737-2025-prac6p:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3040
