apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false
data:
  username: admin1
  MONGO_URI: "mongodb://admin1:password@mongo-0.mongo-headless.default.svc.cluster.local:27017/?replicaSet=rs0"
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
        replSetName: "rs0"
